module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        canvas: "#F5F6F0",
        surface: "#FFFFFF",
        "surface-muted": "#EEF2EC",
        ink: "#192D25",
        muted: "#59685F",
        forest: "#235C3D",
        "forest-strong": "#17442F",
        "forest-soft": "#E7F1EA",
        line: "#DFE6DD",
        positive: "#257A4E",
        "positive-soft": "#E9F5ED",
        warning: "#8A5600",
        "warning-soft": "#FFF2D8",
        critical: "#A63A33",
        "critical-soft": "#FDE9E7",
        info: "#2C6280",
        "info-soft": "#E8F2F8",
        pending: "#67578A",
        "pending-soft": "#F0ECF8",
      },
    },
  },
  plugins: [],
};
