// Vercel runs the repository build before compiling this Fastify entrypoint.
// The generated runtime bundle contains the internal pnpm workspace packages,
// which are otherwise omitted from the deployed Function's file trace.
// @ts-expect-error -- generated by `pnpm build` before this entrypoint runs on Vercel.
await import("../dist/runtime.js");
